### PR TITLE
Fix wrong pandas imports & fix setup.py typo

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
This fixes the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyfinance/utils.py", line 78, in <module>
    from pandas.tseries.frequencies import FreqGroup, get_freq_code
ImportError: cannot import name 'FreqGroup' from 'pandas.tseries.frequencies' (/usr/local/lib/python3.8/site-packages/pandas/tseries/frequencies.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/pyfinance/__init__.py", line 32, in <module>
    from .returns import TFrame, TSeries  # noqa
  File "/usr/local/lib/python3.8/site-packages/pyfinance/returns.py", line 42, in <module>
    from pyfinance import ols, utils
  File "/usr/local/lib/python3.8/site-packages/pyfinance/ols.py", line 15, in <module>
    from pyfinance import utils
  File "/usr/local/lib/python3.8/site-packages/pyfinance/utils.py", line 80, in <module>
    from pandas._libs.tslibs.frequencies import FreqGroup, get_freq_code
ModuleNotFoundError: No module named 'pandas._libs.tslibs.frequencies'
```

**Comment by quantzhang** [comment]
Traceback (most recent call last):
  File "C:/quantzhang_2018-12-13/nuts/BOND/macro Quantamental/bond/III bond beta CFETS.py", line 893, in <module>
    from pyfinance import ols
  File "C:\Program Files\Python35\lib\site-packages\pyfinance\__init__.py", line 32, in <module>
    from .returns import TFrame, TSeries  # noqa
  File "C:\Program Files\Python35\lib\site-packages\pyfinance\returns.py", line 40, in <module>
    from pyfinance import ols, utils
  File "C:\Program Files\Python35\lib\site-packages\pyfinance\ols.py", line 15, in <module>
    from pyfinance import utils
  File "C:\Program Files\Python35\lib\site-packages\pyfinance\utils.py", line 64, in <module>
    from pandas.tseries.frequencies import FreqGroup, get_freq_code
ImportError: cannot import name 'FreqGroup'

**Comment by ghost** [comment]
@quantzhang 

```
Python 3.8.6 (default, Oct 27 2020, 08:57:44) 
[Clang 12.0.0 (clang-1200.0.32.21)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pandas._libs.tslibs.dtypes import FreqGroup
>>> from pandas.tests.tslibs.test_period_asfreq import get_freq_code
>>> import pandas as pd
>>> pd.__version__
'1.1.3'
>>> 
```

**Comment by bsolomon1124** [comment]
Thanks for finding this. I've addressed it in version 1.3.0, which is now available on PyPI. Apologies it was not done sooner.

**Pull request closed without merging**
